# Generated by Django 5.2.5 on 2025-08-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Avis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("service", models.CharField(max_length=255)),
                ("note", models.IntegerField()),
                ("commentaire", models.TextField()),
                ("date", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("prix", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="vehicules/")),
                ("annee", models.IntegerField()),
                ("passagers", models.IntegerField()),
                ("carburant", models.CharField(max_length=50)),
                ("transmission", models.CharField(max_length=50)),
                ("description", models.TextField()),
            ],
        ),
    ]
